
{{ config(materialized='table') }}

SELECT
    E.STATION_ID,
    E.NAME,
    E.LAT,
    E.LON,
    E.ADDRESS,
    E.POST_CODE,
    E.CAPACITY,
    NB.NUM_BIKES_AVAILABLE,
    NB.NUM_BIKES_DISABLED,
    NB.NUM_DOCKS_AVAILABLE,
    NB.NUM_DOCKS_DISABLED,
    NB.LAST_REPORTED,
    NB.STATUS,
    NB.CREATED_AT
FROM
    BICI.PUBLIC.ESTACION E
INNER JOIN
    BICI.PUBLIC.NUM_BICI NB ON E.STATION_ID = NB.STATION_ID
WHERE
    NB.STATUS = 'IN_SERVICE'
