
version: 2

models:
  
  - name: num_bici
    description: "A starter dbt model"
    columns:
      - name: STATION_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null           
